spring:
  mail:
    host: smtp.163.com #SMTP服务器地址
    username: 13711919653@163.com #登陆账号
    password: llg1997729 #登陆密码（或授权码）
    properties:
      mail:
        smtp:
          auth: true
          socketFactory:
            class: javax.net.ssl.SSLSocketFactory
      from:  13711919653@163.com #邮件发信人（即真实邮箱）
    port: 465
  servlet:
    multipart:
      max-file-size: 10MB #限制单个文件大小
      max-request-size: 50MB #限制请求总量